### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Solana0x** [aston668334/nodepay-socks-python#1]
![image](https://github.com/aston668334/nodepay-socks-python/assets/142747768/9658058e-2b52-4f71-b8b6-95f4d874646e)

**Comment by aston668334** [comment]
it seems some problem in proxy one. I justt update a new version. Not sure fix it all ,because i don't have proxy server to test it.

**Comment by Solana0x** [comment]
You also didnt added any proxy auth methods we need some proxy auth method because max proxy have some username and pass

async def main():
    http_proxy = ["http://172.0.0.1:3124",
                  "http://172.0.0.2:3124",
                  "http://172.0.0.3:3124"     
                  ]


we need proxy to be in formate as 

protocol://USername:pass@ip:port

**Comment by Solana0x** [comment]
2024-06-04 19:18:32.009 | ERROR    | __main__:connect_socket_proxy:101 - Connection error: 407 Proxy Authentication Required


i am trying to solve this error for now

**Comment by aston668334** [comment]
According to https://github.com/racinette/websockets_proxy
It should be support like this format. http://login:password@address:port
For not Authentication proxy I test it work well.

**Comment by Solana0x** [comment]
Getting error only 
![image](https://github.com/aston668334/nodepay-socks-python/assets/142747768/4b0e2a00-d04e-4719-bd5b-83e059617faf)

**Comment by Solana0x** [comment]
![image](https://github.com/aston668334/nodepay-socks-python/assets/142747768/b2cc22b8-c618-4744-937d-12f786a589a7)

**Comment by aston668334** [comment]
The error message indicates that the WebSocket connection is being closed with a code 1011 (internal error) due to a keepalive ping timeout. This suggests that the WebSocket server isn't responding to ping messages within the expected time frame, causing the connection to be closed.

you can try 

Increase Ping Interval: Increase the time between ping messages to give the server more time to respond.

**Comment by Solana0x** [comment]
can this be because my proxy provider didnt opened that port for me ? and also to run this which port we neeed to open websocket? or whats the port number ?

could you tell which Proxy provider you are using ?

**Comment by aston668334** [comment]
I use self host proxy
maybe you can try curl -x http://login:password@address:port -L ifconfig.me first for testing

**Comment by Solana0x** [comment]
tried its working in the curl command but not working in the code :(

**Comment by Solana0x** [comment]
May be proxy provider not opened the port? for the server may be we need port nub - 4576 ??

or so ? otherwise idk whats the issue

**Comment by aston668334** [comment]
Which type of proxy do you use?

**Comment by Solana0x** [comment]
i tried everything Socks5 , http, https

**Comment by aston668334** [comment]
later I will test some proxy to find this problem

**Comment by muggle69** [comment]
Please add file proxy instead, 
async def main():
http_proxy = ["http://172.0.0.1:3124",
"http://172.0.0.2:3124",
"http://172.0.0.3:3124"
]
Thank you bro.

**Comment by aston668334** [comment]
done
