### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by doubleTroub1e** [aston668334/nodepay-socks-python#3]
Hi,

I've start no_proxy version at my home raspberry and on remote, on home -everything is working fine, but same setup on remote is failing, this is docker compose setup and I've add 
```
 out = json.loads(response.text)
+logger.info(out)
 USER_ID = out['data'][0]['user_id']
``` 
so that I can see why it can't parse.

```
nodepay-socks-python-nodepay-app-1  | 2024-06-14 12:44:33.737 | INFO     | __main__:<module>:33 - {'success': False, 'code': 403, 'msg': 'Unauthorized', 'data': None}
nodepay-socks-python-nodepay-app-1  | Traceback (most recent call last):
nodepay-socks-python-nodepay-app-1  |   File "/opt/app/nodepay_no_proxy.py", line 34, in <module>
nodepay-socks-python-nodepay-app-1  |     USER_ID = out['data'][0]['user_id']
nodepay-socks-python-nodepay-app-1  | TypeError: 'NoneType' object is not subscriptable
``` 

Do you aware about this, maybe some thoughts on how to fix?

and a side question: Does proxy version works for you? as it doesn't work for me, not sure if this is proxy issue or script.

**Comment by aston668334** [comment]
You may need login in the web extension first.
So that this code can get the device id by that record.

**Comment by doubleTroub1e** [comment]
aha, so this is some kind of blocks for multi ACC usage? 
so that people can't use proxy

**Comment by aston668334** [comment]
I don't know the point.
But first need to login in the web extension, it's that the code need a device record for getting USER_ID in your account.
