### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by burnmine** [aston668334/nodepay-socks-python#6]
![image](https://github.com/aston668334/nodepay-socks-python/assets/76961253/f614b702-5827-4c2a-8755-862a77403f16)

**Comment by aston668334** [comment]
Please provide more information. I have no idea this error occur in witch file. Tnaks

**Comment by jbr1989** [comment]
Same error. 

``
response = requests.request("GET", "https://api.nodepay.ai/api/network/device-networks?page=0&size=10&active=false", headers=headers)
out = json.loads(response.text)
``

The request return a 403 Error.
I get NP_TOKEN by ``localStorage.getItem('np_token');`` and I put in script. 

MANUAL FIX: I have did a manual request and got user_id

**Comment by aston668334** [comment]
> Same error.
> 
> `response = requests.request("GET", "https://api.nodepay.ai/api/network/device-networks?page=0&size=10&active=false", headers=headers) out = json.loads(response.text)`
> 
> The request return a 403 Error. I get NP_TOKEN by `localStorage.getItem('np_token');` and I put in script.
> 
> MANUAL FIX: I have did a manual request and got user_id

Did you using web extention for fist mining? You should first using web. Because it need a device record let code ti get user_id.

**Comment by jbr1989** [comment]
You're right. When I used NP_TOKEN after using the extension.
It looks good.
